id: I3F5A3CF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T16:36:17+00:00'
last_modified: '2022-06-07T12:23:11.058548+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17480
  title: འདུས་པ་མདོ་སོགས་ཀྱི་ཙཀླི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    63C4:
      image_group_id: I4PD646
      title: Volume 1 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 730
      order: 1
      base_file: 63C4.txt
    BDDD:
      image_group_id: I4PD647
      title: Volume 2 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 594
      order: 2
      base_file: BDDD.txt
    6ADB:
      image_group_id: I4PD648
      title: Volume 3 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 584
      order: 3
      base_file: 6ADB.txt
    B7BB:
      image_group_id: I4PD649
      title: Volume 4 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 702
      order: 4
      base_file: B7BB.txt
    5DE6:
      image_group_id: I4PD650
      title: Volume 5 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 552
      order: 5
      base_file: 5DE6.txt
    FCB6:
      image_group_id: I4PD651
      title: Volume 6 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 694
      order: 6
      base_file: FCB6.txt
    5C4E:
      image_group_id: I4PD652
      title: Volume 7 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 184
      order: 7
      base_file: 5C4E.txt
    AD3B:
      image_group_id: I4PD653
      title: Volume 8 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 358
      order: 8
      base_file: AD3B.txt
    AA25:
      image_group_id: I4PD654
      title: Volume 9 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 524
      order: 9
      base_file: AA25.txt
    A8DD:
      image_group_id: I4PD655
      title: Volume 10 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 570
      order: 10
      base_file: A8DD.txt
    52F6:
      image_group_id: I4PD656
      title: Volume 11 of 'dus pa mdo sogs kyi tsak+li/
      total_pages: 856
      order: 11
      base_file: 52F6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
