id: P000584
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17480
  title: འདུས་པ་མདོ་སོགས་ཀྱི་ཙཀླི།
  author: ''
  volumes:
    05708e29cd5545d9964ebf5d583f2b93:
      image_group_id: I4PD646
      title: Volume 1 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 1
      total_pages: 730
      base_file: v001.txt
    3cd99268a28e49199e23f3afbf9ad0e1:
      image_group_id: I4PD647
      title: Volume 2 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 2
      total_pages: 594
      base_file: v002.txt
    31efe2f9f1b64f7f8948b3bae00ce08c:
      image_group_id: I4PD648
      title: Volume 3 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 3
      total_pages: 584
      base_file: v003.txt
    41359f5787ca486fa4b48c4d13da6ec3:
      image_group_id: I4PD649
      title: Volume 4 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 4
      total_pages: 702
      base_file: v004.txt
    85d274e806944ae0a6d6e81b1c355333:
      image_group_id: I4PD650
      title: Volume 5 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 5
      total_pages: 552
      base_file: v005.txt
    85315b1e99a64ab6a9344ec7a63045d7:
      image_group_id: I4PD651
      title: Volume 6 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 6
      total_pages: 694
      base_file: v006.txt
    f6535f4b49db473793086fe1da9b0709:
      image_group_id: I4PD652
      title: Volume 7 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 7
      total_pages: 184
      base_file: v007.txt
    5a404c41d08a4951bb0af60f37d52507:
      image_group_id: I4PD653
      title: Volume 8 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 8
      total_pages: 358
      base_file: v008.txt
    b6bfe06144c548c5ab351f75d58d42d8:
      image_group_id: I4PD654
      title: Volume 9 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 9
      total_pages: 524
      base_file: v009.txt
    190d296b4d0d4ae6a88e3ad65156848b:
      image_group_id: I4PD655
      title: Volume 10 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 10
      total_pages: 570
      base_file: v010.txt
    df521a3d348e4e2b8fba1016f4cd492a:
      image_group_id: I4PD656
      title: Volume 11 of 'dus pa mdo sogs kyi tsak+li/
      volume_number: 11
      total_pages: 856
      base_file: v011.txt
